version: '3.9'

services:
  app_server:
    container_name: app_server
    image: app_server:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    env_file: .env
    ports:
      - '443:443'
      - '9229:9229'
    networks:
      - app-network
    volumes:
      - ./ssl:/usr/src/app/ssl
    restart: unless-stopped
    depends_on:
      - database
  database:
    container_name: app_postgres_dev
    image: postgres:12
    env_file: .env
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - '5431:5431'
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:

volumes:
  postgres-data:
