version: '3'
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - conf:/etc/nginx/conf.d
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=mail@pixartist.de
    network_mode: bridge

  landing-page:
    image: nginx:alpine
    container_name: landing-page
    volumes:
      - ./landing-page:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=www.pixartist.de
      - LETSENCRYPT_HOST=www.pixartist.de
      - VIRTUAL_PORT=80

  api:
    build:
      context: ./api
      dockerfile: dockerfile
    container_name: api
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3000
      - MONGO_ROOT_USER=admin
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_HOST=mongodb
      - DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD}
      - DEFAULT_ADMIN_EMAIL=${DEFAULT_ADMIN_EMAIL}
      - VIRTUAL_HOST=api.pixartist.de
      - LETSENCRYPT_HOST=api.pixartist.de
      - VIRTUAL_PORT=3000
    depends_on:
      - nginx-proxy
      - mongodb

  ddns:
    image: bbaerthlein/docker-ddns-server:latest
    restart: always
    environment:
      - DDNS_ADMIN_LOGIN=admin:${DDNS_ADMIN_LOGIN}
      - DDNS_DOMAINS=ddns.pixartist.de
      - DDNS_PARENT_NS=ns.pixartist.de
      - DDNS_DEFAULT_TTL=3600
      - VIRTUAL_HOST=ddns.pixartist.de,home.ddns.pixartist.de,ns.pixartist.de
      - LETSENCRYPT_HOST=ddns.pixartist.de
      - VIRTUAL_PORT=8080
    ports:
      - "53:53"
      - "53:53/udp"
    volumes:
       - ./bind-data:/var/cache/bind
       - ./database:/root/database

  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}

volumes:
  conf:
  certs:
  vhost:
  html:
  acme:
  mongodb_data:
