version: '3'
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=mail@pixartist.de
    network_mode: bridge

  landing-page:
    image: nginx:alpine
    container_name: landing-page
    ports:
      - 3001:80
    volumes:
      - ./landing-page:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=www.pixartist.de
      - LETSENCRYPT_HOST=www.pixartist.de
      - VIRTUAL_PORT=80

  api:
    build:
      context: ./api
      dockerfile: dockerfile
    container_name: api
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=api.pixartist.de
      - LETSENCRYPT_HOST=api.pixartist.de
      - VIRTUAL_PORT=3000
    depends_on:
      - nginx-proxy

volumes:
  conf:
  certs:
  vhost:
  html:
  acme:
